# Generated by Django 3.2.16 on 2023-01-17 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_post_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
