# Generated by Django 3.2.16 on 2022-12-13 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20221213_0348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='../default_profile_irrizg', upload_to='images/'),
        ),
    ]
